<?php require_once('includes/header.php');?>
<div class="topContainer">
	<div class="welcomeBox"></div>
	<div class="eventDetailhd"><span>Privacy <strong>Policy</strong></span></div>			
	<div class="clr gap"></div>			
			The last update to our Privacy Policy was posted on August 27, 2010.  This Privacy governs the privacy policy of our Website, <a class="lbLink" href="index.php">www.EventGrabber.com</a>, as owned and operated by <strong>Eventgrabber, LLC (Eventgrabber)</strong>.<br><br>
			<span class="detailHd">Definitions</span>
			"Non-Personal Information" (NPI) is information that is not personally identifiable to you and we automatically collect when you access our Website with a web browser.<br><br>
			"Personally Identifiable Information" (PII) is non-public information that is personally identifiable to you and obtained in order for us to provide you with products and services.  PII may include information such as your name, address, phone number, corporate information, credit card information, and other related information that you provide to us.<br><br>
			<span class="detailHd">Overview of Our Service</span>
			<strong>Eventgrabber</strong> offers an online networking service (Service) that allows our Members to receive tailored event advertising to match their personal interests.  We may also sell related products (Products) including items and tickets. Our Privacy Policy relates to the information that you will share with us by using our Service.<br><br>
			<span class="detailHd">Overview of Our Users</span>
			There are two types of customers that interact with us and have the following definitions in this Privacy Policy:  Visitors are customers who navigate to our Website to get more information about our Service, to purchase our Products, or to find out more about <strong>Eventgrabber</strong>.  Members are customers who have completed our registration process and executed necessary agreements with us to use our Service.  Depending on your particular interaction with us, different portions of this Privacy Policy may apply to you at different times.<br><br>
			<span class="detailHd">Our Commitment to Your Privacy</span>
			Our Privacy Policy tells you what PII <strong>Eventgrabber</strong> may collect from you, how we may share your PII, and how you can limit our sharing of your PII.<br><br>
			<strong>Eventgrabber</strong> is committed to providing an exemplary online experience as well as securing the privacy of all our users.  We take your privacy seriously, and we will work with you to ensure that your information is protected.  <strong>Eventgrabber</strong> and our affiliates respect your privacy and recognize the need for appropriate protection and management of your PII you share with us.<br><br>
			<span class="detailHd">Links to Other Websites</span>
			Our Website may contain links to other websites.  You understand that these websites are not under our control and are not subject to our Privacy Policy.  These websites will likely have their own privacy policies.  We have no responsibility for these websites and provide links to these websites solely for your convenience.  You acknowledge that your use and access of these websites is solely at your own risk.  It is your responsibility to check the privacy policies and other legal documents of these websites to see how they treat your personal information.<br><br>
			<span class="detailHd">Information We Collect</span>
			There is no need to reveal or provide any PII when you visit our Website.   You can browse our Website to find out more about <strong>Eventgrabber</strong> and what we do.  As you do so, we may receive and store certain types of NPI as you interact with our Website.  We may also analyze this NPI for trends and statistics as to how people use our Website.<br><br>
			If you decide to join our Website as a Member and thereby use our Service, you will fill out an online form providing such PII as your name, email address, phone, home address, and general demographics as to how you might use our Service.  We will store this information for contacting you.  <strong>Eventgrabber</strong> will also require you to provide a credit card to complete your sign-up for our Service.  Once we have validated your credit card information, you can begin using our Service.<br><br>
			<span class="detailHd">How Information is Used</span>
			We use the PII that you provide for our internal purposes, such as providing you with our Service, fulfilling your orders of our Products, or informing you of new products, services, and offers as provided by us and/or our affiliates.<br><br>
			Our affiliates may have products, services, or offers about which you may be interested in receiving information.  We reserve the right to provide basic contact PII to our affiliate for them to contact you.  If you no longer wish to receive information from our affiliates, you can let us know and we will promptly remove you from further affiliate contact.<br><br>
			We may also combine information you give us through the Service or through printed forms as well as from information we receive about you from other parties.  We will use this combined information to enhance your online experience and to let you know about new products, services, offers, and other promotions.<br><br>
			In order to give you the best possible service, we may use our affiliates to provide contracted services for our business, including, but not limited to processing credit cards, hosting our website, shipping products to you, or advertising.  In many cases, we will need to provide some if not all of the PII you provide to use so that our affiliates can perform these services.  Our affiliates are only authorized to use your PII as provided within this Privacy Policy.  Affiliates that provide such services will have executed non-disclosure agreements with <strong>Eventgrabber</strong> to ensure the protection of your PII.<br><br>
			There are times that we may have to disclose your PII to comply with laws; to assist law enforcement and governmental agencies in preventing or investigating fraud or other crimes, or in response to a court order.  In such instances, we will only provide the PII requested and your PII will only be used for such legal purposes.<br><br>
			Finally, if we sold or transferred our business, we would transfer your PII to the purchaser as appropriate and might also retain a copy of your PII for any new business ventures we would start.<br><br>
			<span class="detailHd">Changing Your Information</span>
			You may change your PII at any time using facilities found on our Website, including removing yourself from mailing lists.  If at any time you need assistance, just send us an email with your request.<br><br>
			<span class="detailHd">Opting Out of Sharing Information</span>
			You can always opt out of future unaffiliated third-party disclosures of your information.  Such opt-out will not affect disclosures otherwise permitted by law including but not limited to:<br>
			<strong>(i)</strong> disclosures to affiliates,<br>
			<strong>(ii)</strong> disclosures to third-party service providers who provide certain services for our business, such as credit card processing, computer system services, shipping, data management, or promotional services, <br>
			<strong>(iii)</strong> disclosures to third parties as necessary to fulfill your requests, (iv) disclosures to governmental agencies or law enforcement departments or otherwise required to be made under applicable law, (v) previously completed disclosures to third parties, or<br>
			<strong>(vi)</strong> disclosures to third parties in connection with subsequent contests or promotions you may choose to enter, or third-party offers you may choose to accept.<br><br>
			<span class="detailHd">Protecting Your Child's Privacy</span>
			We follow the United States' Children's Online Privacy Protection Act (COPPA).  Even though our Services are not designed for use by anyone under the age of 18 (child), we realize that a child may attempt to access our Services.  We do not knowing collect PII from a child; however, you acknowledge that we do not verify the age of our users nor do we have any liability to do so.  If you are parent who suspects their child is attempting to use our Services, please contact us immediately.  If you are a child, please do not attempt to use our Services.<br><br>
			<span class="detailHd">Our Email Policy</span>
			Our affiliates and we fully comply with the United States' CAN-SPAM Act.  You can always opt out of receipt of further email correspondence from us or affiliates.  We will not sell, rent, or trade your email address to any unaffiliated third-party without your permission.  You understand that email is not considered a secure form of communication.  Generally, any information you disclose in an email may be viewed by hackers while such information is en route to us.   As such, take care in what you disclose in any email that you send to us.<br><br>
			<span class="detailHd">Our Security Policy</span>
			We have constructed our Website and Service using sophisticated encryption and authentication tools to protect your PII.   When we collect your PII through our Website, we encrypt it and prevent unauthorized access to it by using industry standard technologies, such as encryption software, routers and firewalls.  Unfortunately, due to the vary nature of the Internet and hackers, we cannot completely guarantee that your PII is 100% protected.  Once we receive your PII, we have industry standard security measures and polices that protect against the loss or misuse of your PII; again, we cannot completely guarantee against such loss or misuse.  We strongly urge you to protect any password you may have for our Service and not share it with anyone.  You should always log out of our Service when you are done using it, especially if you are sharing a computer with someone else or are using a public computer.<br><br>
			<span class="detailHd">Use of Credit Cards</span>
			You may have to provide a credit card to purchase our products or Service.  We use third-party billing services and HAVE NO CONTROL over these services.  We use commercially reasonable efforts to make sure that your credit card number is kept STRICTLY CONFIDENTIAL by using only third-party billing services that use industry-standard encryption technology to protect your credit card number from unauthorized use.  However, you understand and agree that we are in no way responsible for any misuse of your credit card number.<br><br>
			<span class="detailHd">Cookies</span>
			Our Website may send a "cookie" to your computer.  A cookie is a small piece of data that is sent to your browser from a web server and stored on your computer's hard drive.  A cookie cannot read data off your hard disk or read cookie files created by other sites. Cookies do not damage your system.  We use cookies to identify which areas of our site you have visited, so the next time you visit the site, we can better personalize the content that you see on our Website.  Most browser software can be set to disable the use of Cookies.  However, if you disable Cookies, you may not be able to use certain functionality on our Website correctly or at all.  We never place PII in Cookies.<br><br>
			<span class="detailHd">Web Beacons</span>
			We may also use web beacons to collect NPI about your use of our Website as well as those of our affiliates, and your use of special promotions or newsletters. The information we collect by Web Beacons allows us to statistically monitor the number of people that open our emails and why they opened our emails.  Our Web Beacons are not used to track your activity outside of our Website or those of our affiliates.  We do not link NPI from Web Beacons to PII without your permission.<br><br>
			<span class="detailHd">Changes to Our Privacy Policy</span>
			As necessary to address changes in laws as well as our business practices, we may modify our Privacy Policy, in whole or in part, to address these changes.  We will typically notify users by some message on our Website home page that our Privacy Policy has changed.  We will also change the "Last Updated" date at the beginning of this Privacy Policy.  Any changes we make to our Privacy Policy are effective as of this Last Updated date and replace any prior Privacy Policies.  We encourage you to review our Privacy Policy periodically to make sure you still agree with it.
			<br><br>
			<span class="detailHd">Questions About Our Privacy Policy</span>
			If you have any questions about our Privacy Policy, please contact us using the Contact Us form as found on our Website.
</div>
</div>
<?php require_once('includes/footer.php');?>